
const API='https://open-close-map-api.onrender.com';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const fallbackMap={'ラーメン':'assets/ramen.png','カフェ':'assets/cafe.png','居酒屋':'assets/izakaya.png','焼肉':'assets/yakiniku.png','美容':'assets/beauty.png','コンビニ':'assets/convenience.png','テナント':'assets/tenant.png'};
function imageFor(x){return x.image_url||fallbackMap[x.category]||fallbackMap['テナント']}
function label(s){return {opening:'開店予定',open:'OPEN',closing:'閉店予定',closed:'閉店',tenant:'テナント'}[s]||s||'店舗情報'}
function render(items){$('grid').innerHTML=items?.length?items.map(x=>`<article class="store-card" data-id="${x.id}"><div class="store-image" style="background-image:url('${esc(imageFor(x))}')"><span class="badge ${esc(x.status)}">${esc(label(x.status))}</span></div><div class="store-body"><div class="store-name">${esc(x.name||'店舗名未確認')}</div><div class="store-meta">${esc(x.open_date||x.close_date||'日付未確認')}<br>${esc([x.prefecture,x.city].filter(Boolean).join(' ')||'エリア未確認')}</div><div class="store-tags">${x.category?`<span class="store-tag">${esc(x.category)}</span>`:''}${x.confidence?`<span class="store-tag">確度 ${esc(x.confidence)}%</span>`:''}</div></div></article>`).join(''):'<div class="empty">表示できる店舗情報がありません。</div>';document.querySelectorAll('.store-card').forEach(c=>c.onclick=()=>location.href=`detail.html?id=${encodeURIComponent(c.dataset.id)}`)}
async function getJSON(u){const r=await fetch(u);if(!r.ok)throw new Error(r.status);return r.json()}
async function stats(){const d=await getJSON(API+'/api/stats');$('storesTotal').textContent=d.stores_total??0;$('discoveryTotal').textContent=d.discovery_unprocessed??0;$('todayOpen').textContent=d.today_open??0;$('weekOpen').textContent=d.week_open??0;$('weekClose').textContent=d.week_close??0;$('tenant').textContent=d.tenant_detected??0}
async function stores(params={}){const q=new URLSearchParams({limit:'40'});Object.entries(params).forEach(([k,v])=>v&&q.set(k,v));const d=await getJSON(API+'/api/stores?'+q);render(d.items||[])}
async function search(){const q=$('q').value.trim();if(!q)return stores();const d=await getJSON(API+'/api/stores?limit=200');render((d.items||[]).filter(x=>[x.name,x.category,x.prefecture,x.city,x.address].filter(Boolean).join(' ').toLowerCase().includes(q.toLowerCase())))}
$('search').onclick=search;$('q').onkeydown=e=>{if(e.key==='Enter')search()};document.querySelectorAll('[data-pref]').forEach(b=>b.onclick=()=>stores({prefecture:b.dataset.pref}));document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=async()=>{const d=await getJSON(API+'/api/stores?limit=200');render((d.items||[]).filter(x=>x.category===b.dataset.cat))});Promise.all([stats(),stores()]);
